// Create account profile
###
POST http://localhost:3000/api/v1/user/auth/register HTTP/1.1
content-type: application/json

{
  "firstName": "Anthony",
  "lastName": "Legg",
  "email": "leggtc1@student.op.ac.nz",
  "userName": "leggtc1",
  "role": "ADMIN_USER",
  "password": "Yogi##@4tdfg",
  "confirmPassword": "Yogi##@4tdfg",
  "profileImgURL": "https://randomuser.me/api/portraits/men/80.jpg"
}

// Login + Get Auth Token
###
POST http://localhost:3000/api/v1/user/auth/login HTTP/1.1
content-type: application/json

{
  "userName": "leggtc1",
  "password": "Yogi##@4tdfg"
}

// Replace Bearer Token
// Run the user seeder request
### 
GET http://localhost:3000/api/v1/user/auth/admin/seeder/players HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU1YjA2YzA0LTMzMTItNDFiZC1hZWQ5LTQyMDMwNDc1NGFhZSIsInJvbGUiOiJBRE1JTl9VU0VSIiwidXNlck5hbWUiOiJsZWdndGMxIiwiaWF0IjoxNjc1NDc5ODUwLCJleHAiOjE2NzU0ODM0NTB9.YciR3c1n34iCBnEyXaFmN7bxNPD5wtYPgP1yRefAyIo

// Replace Bearer Token
// Run the category seeder request
### 
GET http://localhost:3000/api/v1/user/auth/admin/seeder/categories HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU1YjA2YzA0LTMzMTItNDFiZC1hZWQ5LTQyMDMwNDc1NGFhZSIsInJvbGUiOiJBRE1JTl9VU0VSIiwidXNlck5hbWUiOiJsZWdndGMxIiwiaWF0IjoxNjc1NDc5ODUwLCJleHAiOjE2NzU0ODM0NTB9.YciR3c1n34iCBnEyXaFmN7bxNPD5wtYPgP1yRefAyIo
