###
POST http://localhost:3000/api/v1/user/auth/register HTTP/1.1
content-type: application/json

{
  "firstName": "Anthony",
  "lastName": "Legg",
  "email": "leggtc1@student.op.ac.nz",
  "userName": "leggtc1",
  "role": "ADMIN_USER",
  "password": "Yogi##@4tdfg",
  "confirmPassword": "Yogi##@4tdfg",
  "profileImgURL": "https://randomuser.me/api/portraits/men/75.jpg"
}

###
POST http://localhost:3000/api/v1/user/auth/login HTTP/1.1
content-type: application/json

{
  "userName": "leggtc1",
  "password": "Yogi##@4tdfg"
}

###
POST http://localhost:3000/api/v1/user/auth/login HTTP/1.1
content-type: application/json

{
  "email": "leggtc1@student.op.ac.nz",
  "password": "Yogi##@4tdfg"
}

###
POST http://localhost:3000/api/v1/user/auth/register HTTP/1.1
content-type: application/json

{
  "firstName": "Grayson",
  "lastName": "Orr",
  "email": "grayorr@op.ac.nz",
  "userName": "grayorr",
  "role": "ADMIN_USER",
  "password": "dfgdfgsBIT%2022",
  "confirmPassword": "dfgdfgsBIT%2022",
  "profileImgURL": "https://randomuser.me/api/portraits/men/85.jpg"
}

###
POST http://localhost:3000/api/v1/user/auth/login HTTP/1.1
content-type: application/json

{
  "userName": "grayorr",
  "password": "dfgdfgsBIT%2022"
}

###
POST http://localhost:3000/api/v1/user/auth/login HTTP/1.1
content-type: application/json

{
  "email": "grayorr@op.ac.nz",
  "password": "dfgdfgsBIT%2022"
}

// get admin user profile by username
### 
GET http://localhost:3000/api/v1/user/auth/quizadmin/details/userName/grayorr HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkZTc3NjI0LTE1Y2MtNGM4MC05ZDdlLTYzZjQ4YTY0NWU0NyIsInJvbGUiOiJCQVNJQ19VU0VSIiwidXNlck5hbWUiOiJ5b2dpbnoxIiwiaWF0IjoxNjcxNjU2MDYxLCJleHAiOjE2NzE2NTk2NjF9.hEaa4Cxp9fUl0b_yaIUBhhtpPOQqUcRwylcfG-gs1tI

// get admin user profile by email
### 
GET http://localhost:3000/api/v1/user/auth/quizadmin/details/email/grayorr@op.ac.nz HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkZTc3NjI0LTE1Y2MtNGM4MC05ZDdlLTYzZjQ4YTY0NWU0NyIsInJvbGUiOiJCQVNJQ19VU0VSIiwidXNlck5hbWUiOiJ5b2dpbnoxIiwiaWF0IjoxNjcxNjU2MDYxLCJleHAiOjE2NzE2NTk2NjF9.hEaa4Cxp9fUl0b_yaIUBhhtpPOQqUcRwylcfG-gs1tI


// get basic user profile by username
### 
GET http://localhost:3000/api/v1/user/auth/quizadmin/details/userName/cgrzesiewicz3 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMwNGIyYzI1LWY2MWQtNGEyNi1iNTE2LTQyODEyZDVjZmIxMiIsInJvbGUiOiJBRE1JTl9VU0VSIiwidXNlck5hbWUiOiJsZWdndGMxIiwiaWF0IjoxNjcxNTc2OTQ1LCJleHAiOjE2NzE1ODA1NDV9.y9k-ZBFN8HeKqwPYWDGYd6CQZRC3Jm2J0PkDH-H9-8g

// get basic user profile by email
### 
GET http://localhost:3000/api/v1/user/auth/quizadmin/details/email/cgrzesiewicz3@unesco.org HTTP/1.1
content-type: application/json
Authorization: Bearer 

// get current user via token
### 
GET http://localhost:3000/api/v1/user/auth/details HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkZTc3NjI0LTE1Y2MtNGM4MC05ZDdlLTYzZjQ4YTY0NWU0NyIsInJvbGUiOiJCQVNJQ19VU0VSIiwidXNlck5hbWUiOiJ5b2dpbnoxIiwiaWF0IjoxNjcxNjU2MDYxLCJleHAiOjE2NzE2NTk2NjF9.hEaa4Cxp9fUl0b_yaIUBhhtpPOQqUcRwylcfG-gs1tI