// Delete current user via valid token
### 
DELETE http://localhost:3000/api/v1/user/auth/details HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkwYjRhMmUxLTMxNDgtNDM5Ni1iYjdjLTE3MDhiZTQ3Y2VlNiIsInJvbGUiOiJBRE1JTl9VU0VSIiwidXNlck5hbWUiOiJsZWdndGMxIiwiaWF0IjoxNjcxNjcxMjU4LCJleHAiOjE2NzE2NzQ4NTh9.0zb1r4mpB3uHwU3rJR4mINBdQK37NWnbfs8ByeztBS8

// Delete basic user profile by username
### 
DELETE http://localhost:3000/api/v1/user/auth/quizadmin/details/userName/hburstow6 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkwYjRhMmUxLTMxNDgtNDM5Ni1iYjdjLTE3MDhiZTQ3Y2VlNiIsInJvbGUiOiJBRE1JTl9VU0VSIiwidXNlck5hbWUiOiJsZWdndGMxIiwiaWF0IjoxNjcxNjcxMjU4LCJleHAiOjE2NzE2NzQ4NTh9.0zb1r4mpB3uHwU3rJR4mINBdQK37NWnbfs8ByeztBS8

// Delete basic user profile by email
### 
DELETE http://localhost:3000/api/v1/user/auth/quizadmin/details/email/gowers8@theguardian.com HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkwYjRhMmUxLTMxNDgtNDM5Ni1iYjdjLTE3MDhiZTQ3Y2VlNiIsInJvbGUiOiJBRE1JTl9VU0VSIiwidXNlck5hbWUiOiJsZWdndGMxIiwiaWF0IjoxNjcxNjcxMjU4LCJleHAiOjE2NzE2NzQ4NTh9.0zb1r4mpB3uHwU3rJR4mINBdQK37NWnbfs8ByeztBS8


// delete admin user profile by username
// this should fail
### 
DELETE http://localhost:3000/api/v1/user/auth/quizadmin/details/userName/grayorr HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkwYjRhMmUxLTMxNDgtNDM5Ni1iYjdjLTE3MDhiZTQ3Y2VlNiIsInJvbGUiOiJBRE1JTl9VU0VSIiwidXNlck5hbWUiOiJsZWdndGMxIiwiaWF0IjoxNjcxNjcxMjU4LCJleHAiOjE2NzE2NzQ4NTh9.0zb1r4mpB3uHwU3rJR4mINBdQK37NWnbfs8ByeztBS8

// Delete other admin user profile by email
// this should fail
### 
DELETE http://localhost:3000/api/v1/user/auth/quizadmin/details/email/grayorr@op.ac.nz HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkwYjRhMmUxLTMxNDgtNDM5Ni1iYjdjLTE3MDhiZTQ3Y2VlNiIsInJvbGUiOiJBRE1JTl9VU0VSIiwidXNlck5hbWUiOiJsZWdndGMxIiwiaWF0IjoxNjcxNjcxMjU4LCJleHAiOjE2NzE2NzQ4NTh9.0zb1r4mpB3uHwU3rJR4mINBdQK37NWnbfs8ByeztBS8