// Create account profile
###
POST http://localhost:3000/api/v1/user/auth/register HTTP/1.1
content-type: application/json

{
  "firstName": "Anthony",
  "lastName": "Legg",
  "email": "leggtc1@student.op.ac.nz",
  "userName": "leggtc1",
  "role": "ADMIN_USER",
  "password": "Yogi##@4tdfg",
  "confirmPassword": "Yogi##@4tdfg",
  "profileImgURL": "https://randomuser.me/api/portraits/men/80.jpg"
}
// Login + Get Auth Token
###
POST http://localhost:3000/api/v1/user/auth/login HTTP/1.1
content-type: application/json

{
  "userName": "leggtc1",
  "password": "Yogi##@4tdfg"
}

// Replace Bearer Token
// Run the user seeder request
### 
GET http://localhost:3000/api/v1/user/auth/admin/seeder/players HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgxOTk3Mzc1LWFlODMtNDAzYy1iNGZiLWQ4NzY3Yzg3N2Q5ZSIsInJvbGUiOiJBRE1JTl9VU0VSIiwidXNlck5hbWUiOiJsZWdndGMxIiwiaWF0IjoxNjcyMTA5NDMyLCJleHAiOjE2NzIxMTMwMzJ9.iJvBdCAej8AYvhRdzVn-xL_hAZAxNfQna9QQ0XC7A9I

// Replace Bearer Token
// Run the category seeder request
### 
GET http://localhost:3000/api/v1/user/auth/admin/seeder/categories HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZjMTA5NDhiLTZkY2ItNGIyZC04ZTY3LTlmYzUxNjlhNWE0NCIsInJvbGUiOiJCQVNJQ19VU0VSIiwidXNlck5hbWUiOiJ5b2dpbnoxIiwiaWF0IjoxNjcyMTEwNjc2LCJleHAiOjE2NzIxMTQyNzZ9.PABKBqhkl-LAm4a5el6uhRYkLEqVgdmoGrxWmsVaGbo
