// Delete current user via valid token
### 
DELETE http://localhost:3000/api/v1/user/auth/details HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRhYWMyMGY0LTUxMmMtNGEzZi1hMDM4LWNhZDI0ZGExMGI0YiIsInJvbGUiOiJBRE1JTl9VU0VSIiwidXNlck5hbWUiOiJsZWdndGMxIiwiaWF0IjoxNjcxNjU3ODA0LCJleHAiOjE2NzE2NjE0MDR9.JVpI6dBU-h4Q3s9msMVO120HzEUKI_mKOWx9OZwc7Bk

// Delete basic user profile by username
### 
DELETE http://localhost:3000/api/v1/user/auth/quizadmin/details/userName/cgrzesiewicz3 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRhYWMyMGY0LTUxMmMtNGEzZi1hMDM4LWNhZDI0ZGExMGI0YiIsInJvbGUiOiJBRE1JTl9VU0VSIiwidXNlck5hbWUiOiJsZWdndGMxIiwiaWF0IjoxNjcxNjU3ODA0LCJleHAiOjE2NzE2NjE0MDR9.JVpI6dBU-h4Q3s9msMVO120HzEUKI_mKOWx9OZwc7Bk

// Delete basic user profile by email
### 
DELETE http://localhost:3000/api/v1/user/auth/quizadmin/details/email/cgrzesiewicz3@unesco.org HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRhYWMyMGY0LTUxMmMtNGEzZi1hMDM4LWNhZDI0ZGExMGI0YiIsInJvbGUiOiJBRE1JTl9VU0VSIiwidXNlck5hbWUiOiJsZWdndGMxIiwiaWF0IjoxNjcxNjU3ODA0LCJleHAiOjE2NzE2NjE0MDR9.JVpI6dBU-h4Q3s9msMVO120HzEUKI_mKOWx9OZwc7Bk


// delete admin user profile by username
// this should fail
### 
DELETE http://localhost:3000/api/v1/user/auth/quizadmin/details/userName/grayorr HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRhYWMyMGY0LTUxMmMtNGEzZi1hMDM4LWNhZDI0ZGExMGI0YiIsInJvbGUiOiJBRE1JTl9VU0VSIiwidXNlck5hbWUiOiJsZWdndGMxIiwiaWF0IjoxNjcxNjU3ODA0LCJleHAiOjE2NzE2NjE0MDR9.JVpI6dBU-h4Q3s9msMVO120HzEUKI_mKOWx9OZwc7Bk

// Delete other admin user profile by email
// this should fail
### 
DELETE http://localhost:3000/api/v1/user/auth/quizadmin/details/email/grayorr@op.ac.nz HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRhYWMyMGY0LTUxMmMtNGEzZi1hMDM4LWNhZDI0ZGExMGI0YiIsInJvbGUiOiJBRE1JTl9VU0VSIiwidXNlck5hbWUiOiJsZWdndGMxIiwiaWF0IjoxNjcxNjU3ODA0LCJleHAiOjE2NzE2NjE0MDR9.JVpI6dBU-h4Q3s9msMVO120HzEUKI_mKOWx9OZwc7Bk