### 
POST http://localhost:3000/api/v1/user/auth/register HTTP/1.1
content-type: application/json

{
  "firstName": "Anthony",
  "lastName": "Legg",
  "email": "leggtc1@student.op.ac.nz",
  "userName": "leggtc1",
  "role": "BASIC_USER",
  "password": "Version@10019045",
  "confirmPassword": "Version@10019045",
  "profileImgURL": "https://randomuser.me/api/portraits/men/79.jpg"
}
### 
POST http://localhost:3000/api/v1/user/auth/login HTTP/1.1
content-type: application/json

{
  "email": "leggtc1@student.op.ac.nz",
  "password": "Version@10019045"
}

###
POST http://localhost:3000/api/v1/user/auth/register HTTP/1.1
content-type: application/json

{
  "firstName": "Yogi",
  "lastName": "Legg",
  "email": "yoginz1@student.op.ac.nz",
  "userName": "yoginz1",
  "role": "ADMIN_USER",
  "password": "Shady@10019045",
  "confirmPassword": "Shady@10019045",
  "profileImgURL": "https://randomuser.me/api/portraits/men/80.jpg"
}

### 
POST http://localhost:3000/api/v1/user/auth/login HTTP/1.1
content-type: application/json

{
  "email": "yoginz1@student.op.ac.nz",
  "password": "Shady@10019045"
}
// Run the seeder request
### 
GET http://localhost:3000/api/v1/user/auth/admin/seeder HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE4MmE3NjI5LWIzNWEtNGU2NS04MTk4LTEwMDg0NzBkYTAxOSIsInJvbGUiOiJBRE1JTl9VU0VSIiwidXNlck5hbWUiOiJ5b2dpbnoxIiwiaWF0IjoxNjcxNDMzMjMzLCJleHAiOjE2NzE0MzY4MzN9.2l9T88WEiAoZA81ViZieCGdZ2eH-JunYvZHD_veourU
### 
