### 
POST http://localhost:3000/api/v1/user/auth/register HTTP/1.1
content-type: application/json

{
  "firstName": "Yogi",
  "lastName": "Legg",
  "email": "yoginz1@student.op.ac.nz",
  "userName": "yoginz1",
  "role": "BASIC_USER",
  "password": "vZ8}LGK%wx",
  "confirmPassword": "vZ8}LGK%wx",
  "profileImgURL": "https://randomuser.me/api/portraits/men/79.jpg"
}
### 
POST http://localhost:3000/api/v1/user/auth/login HTTP/1.1
content-type: application/json

{
  "email": "yoginz1@student.op.ac.nz",
  "password": "vZ8}LGK%wx"
}

### 
POST http://localhost:3000/api/v1/user/auth/login HTTP/1.1
content-type: application/json

{
  "userName": "yoginz1",
  "password": "vZ8}LGK%wx"

}

// Update User With Token
### 
PUT  http://localhost:3000/api/v1/user/auth/details HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIyMmFkY2IzLTRjNzItNDRmOS05YjVmLTYxMzRhZmFhMmFhMyIsInJvbGUiOiJCQVNJQ19VU0VSIiwidXNlck5hbWUiOiJ5b2dpbnoxIiwiaWF0IjoxNjcxNjcwMTQzLCJleHAiOjE2NzE2NzM3NDN9.Lx7YTl8ZfQmxNcc86mFjst5Os96rySa22qcJYRVcqF0
### 

// Delete current user via valid token
### 
DELETE http://localhost:3000/api/v1/user/auth/details HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRlZTQ2Mzc3LTg4ZDMtNDFiMC1hZGVjLWFiMmFhMTg2MzQzNSIsInJvbGUiOiJCQVNJQ19VU0VSIiwidXNlck5hbWUiOiJ5b2dpbnoxIiwiaWF0IjoxNjcxNjcwMjY2LCJleHAiOjE2NzE2NzM4NjZ9.csyFRj5IpQCX4aCBc2J79mW7EpUisbwJa6WYjeD37iM