### 
POST http://localhost:3000/api/v1/user/auth/register HTTP/1.1
content-type: application/json

{
  "firstName": "Yogi",
  "lastName": "Legg",
  "email": "yoginz1@student.op.ac.nz",
  "userName": "yoginz1",
  "role": "BASIC_USER1",
  "password": "vZ8}LGK%wx",
  "confirmPassword": "vZ8}LGK%wx",
  "profileImgURL": "https://randomuser.me/api/portraits/men/79.jpg"
}
### 
POST http://localhost:3000/api/v1/user/auth/register HTTP/1.1
content-type: application/json

{
  "firstName": "Y",
  "lastName": "L",
  "email": "yoginz1@student.op.ac.nz",
  "userName": "yoginz1",
  "role": "BASIC_USER",
  "password": "vZ8}LGK%wx",
  "confirmPassword": "vZ8}LGK%wx",
  "profileImgURL": "https://randomuser.me/api/portraits/men/79.jpg"
}

### 
POST http://localhost:3000/api/v1/user/auth/register HTTP/1.1
content-type: application/json

{
  "firstName": "Yogi",
  "lastName": "Legg",
  "email": "yogi@student.op.ac.nz",
  "userName": "yoginz",
  "role": "BASIC_USER",
  "password": "vZ8}LGK%wx",
  "confirmPassword": "vZ8}LGK%wx",
  "profileImgURL": "https://randomuser.me/api/portraits/men/79.jpg"
}

### 
POST http://localhost:3000/api/v1/user/auth/register HTTP/1.1
content-type: application/json

{
  "firstName": "Yogi",
  "lastName": "Legg",
  "email": "yogi.student.op.ac.nz",
  "userName": "yogi1",
  "role": "BASIC_USER",
  "password": "vZ8}LGK%wx",
  "confirmPassword": "vZ8}LGK%wx",
  "profileImgURL": "https://randomuser.me/api/portraits/men/79.jpg"
}

### 
POST http://localhost:3000/api/v1/user/auth/register HTTP/1.1
content-type: application/json

{
  "firstName": "Yogi",
  "lastName": "Legg",
  "email": "yogi1@student.op.ac.nz",
  "userName": "yogi1",
  "role": "BASIC_USER",
  "password": "vZ8}LGK",
  "confirmPassword": "vZ8}LGK%wx",
  "profileImgURL": "https://randomuser.me/api/portraits/men/79.jpg"
}

// get admin user profile by username
### 
GET http://localhost:3000/api/v1/user/auth/admin/details/userName/grayorr HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkZTc3NjI0LTE1Y2MtNGM4MC05ZDdlLTYzZjQ4YTY0NWU0NyIsInJvbGUiOiJCQVNJQ19VU0VSIiwidXNlck5hbWUiOiJ5b2dpbnoxIiwiaWF0IjoxNjcxNjU2MDYxLCJleHAiOjE2NzE2NTk2NjF9.hEaa4Cxp9fUl0b_yaIUBhhtpPOQqUcRwylcfG-gs1tI

// get admin user profile by email
### 
GET http://localhost:3000/api/v1/user/auth/admin/details/email/grayorr@op.ac.nz HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkZTc3NjI0LTE1Y2MtNGM4MC05ZDdlLTYzZjQ4YTY0NWU0NyIsInJvbGUiOiJCQVNJQ19VU0VSIiwidXNlck5hbWUiOiJ5b2dpbnoxIiwiaWF0IjoxNjcxNjU2MDYxLCJleHAiOjE2NzE2NTk2NjF9.hEaa4Cxp9fUl0b_yaIUBhhtpPOQqUcRwylcfG-gs1tI

// get basic user profile by username
### 
GET http://localhost:3000/api/v1/user/auth/admin/details/userName/cgrzesiewicz3 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMwNGIyYzI1LWY2MWQtNGEyNi1iNTE2LTQyODEyZDVjZmIxMiIsInJvbGUiOiJBRE1JTl9VU0VSIiwidXNlck5hbWUiOiJsZWdndGMxIiwiaWF0IjoxNjcxNTc2OTQ1LCJleHAiOjE2NzE1ODA1NDV9.y9k-ZBFN8HeKqwPYWDGYd6CQZRC3Jm2J0PkDH-H9-8g

// get basic user profile by email
### 
GET http://localhost:3000/api/v1/user/auth/admin/details/email/cgrzesiewicz3@unesco.org HTTP/1.1
content-type: application/json
Authorization: Bearer 

// get current user via token
### 
GET http://localhost:3000/api/v1/user/auth/details HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkZTc3NjI0LTE1Y2MtNGM4MC05ZDdlLTYzZjQ4YTY0NWU0NyIsInJvbGUiOiJCQVNJQ19VU0VSIiwidXNlck5hbWUiOiJ5b2dpbnoxIiwiaWF0IjoxNjcxNjU2MDYxLCJleHAiOjE2NzE2NTk2NjF9.hEaa4Cxp9fUl0b_yaIUBhhtpPOQqUcRwylcfG-gs1tI